from ubuntu:18.04

run apt-get -qq update
run apt-get install -qq --no-install-recommends xinetd rsyslog software-properties-common
run apt-get install -y netcat-traditional htop

run apt-get install -y python3.6

copy exploit /
copy test.py /
copy exploit.sh /
copy test1.sh /
copy test2.sh /
copy test3.sh /
copy test4.sh /



